[manifest]
version = "1.0.0"
dump_lua = true
priority = -10

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.added_to_deck = nil"
position = "after"
payload = '''
self.triggers = 0
self.hogged_out = false
'''
match_indent = true
times = 1