[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "current_round = {"
position = "after"
payload = '''
    hogwild = false,
'''
match_indent = true
times = 1