[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = '''
if ret and type(ret) == "table" and ret.repetitions then
    G.CARD_CALC_COUNTS[ret.card] = G.CARD_CALC_COUNTS[ret.card] or {1,1}
    G.CARD_CALC_COUNTS[ret.card][2] = G.CARD_CALC_COUNTS[ret.card][2] + ret.repetitions
end
'''
position = "at"
payload = '''
if ret and type(ret) == "table" and ret.repetitions then
    local HawgWild = 0
    if SMODS.find_card(crew_hogwild, false) then
        print("HAWGWILD (main_patch)")
        G.GAME.current_round.hogwild = true
        HawgWild = 1
    end
    G.CARD_CALC_COUNTS[ret.card] = G.CARD_CALC_COUNTS[ret.card] or {1,1}
    G.CARD_CALC_COUNTS[ret.card][2] = G.CARD_CALC_COUNTS[ret.card][2] + ret.repetitions + HawgWild
end
'''
match_indent = true
times = 1