[manifest]
version = "1.0.0"
priority = -1
dump_lua = true

# Define a var substitution rule. This searches for lines that contain {{lovely:var_name}}

[vars]
numerator = "1"
denominator= "20"

# Inject one or more lines of code before, after, or at (replacing) a line which matches
# the provided pattern.

[[patches]]
[patches.pattern]
#Checks if Moai should appear
target = "card.lua"
pattern = "self.opening = true"
position = "after"
match_indent = true
payload = '''

local moai_time = false

if G.GAME.stake >= 3 and (pseudorandom("MoaiTime") < ({{lovely:numerator}}/{{lovely:denominator}})) then
    moai_time = true
end

G.GAME.moai_time = moai_time

'''

[[patches]]
[patches.pattern]
#Only one card appears
target = "card.lua"
pattern = '''local _size = self.ability.extra'''
position = "after"
match_indent = true
payload = '''
if moai_time then
    _size = 1
    G.GAME.pack_choices = 1
end
'''

[[patches]]
[patches.pattern]
#Hijacks Booster code to spawn Moai.
target = "card.lua"
pattern = '''if booster_obj.create_card and type(booster_obj.create_card) == "function" then'''
position = "at"
match_indent = true
payload = '''
if moai_time then
    local key_override = "c_crew_dumdum"
    if (pseudorandom("bombtime") < (1/40)) and G.GAME.stake > 3 then key_override = "c_crew_500kg" end
    card = SMODS.create_card({set = "Spectral", area = G.pack_cards, skip_materialize = true, soulable = false, key = key_override, key_append = "spe"})
elseif booster_obj.create_card and type(booster_obj.create_card) == "function" then
'''

[[patches]]
[patches.pattern]
#Creates a global variable on game_init (G.GAME.moai_time)
target = "game.lua"
pattern = "won = false,"
position = "after"
match_indent = true
payload = '''
moai_time = false,
'''

[[patches]]
[patches.pattern]
#Keeps the skip button disabled when the spectral pack is opened
target = "functions/button_callbacks.lua"
pattern = "if G.pack_cards and (not (G.GAME.STOP_USE and G.GAME.STOP_USE > 0)) and"
position = "after"
match_indent = true
payload = '''
not G.GAME.moai_time and
'''