[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
function end_round()
    G.E_MANAGER:add_event(Event({
      trigger = 'after',
      delay = 0.2,
      func = function()
'''
position = "after"
payload = '''
        print("HAWGWILD reset")
        G.GAME.current_round.hogwild = false
'''
match_indent = true
times = 1